name: Build and upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  build_and_deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    environment: release

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build tox pex
    - name: Run checks with tox
      run: tox
    - name: Build an executable with pex
      run: mkdir bin && pex . -o bin/krypt-${{ runner.os }} -r deps.txt -e krypt.main:launch
    - name: Upload krypt executable
      uses: actions/upload-artifact@v4
      with:
        name: krypt-${{ runner.os }}
        path: bin/krypt-${{ runner.os }}
        retention-days: 7
    - name: Add the executable to release assets
      uses: softprops/action-gh-release@v2
      with:
        files: bin/krypt-${{ runner.os }}
    - name: Build package
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
